### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by antiapt** [wolterlw/hand_tracking#28]
I was following the instructions and trying to reproduce the examples.  But it raises a recursion error when calling the sigmoid function [here](https://github.com/wolterlw/hand_tracking/blob/0cccb81e620f602e1a8f91aaed525e20b809fdf5/hand_tracker.py#L125).

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Desktop\temp\hand_tracking\hand_tracker.py", line 170, in __call__
    source, keypoints = self.detect_hand(img_norm)
  File "C:\Users\user\Desktop\temp\hand_tracking\hand_tracker.py", line 125, in detect_hand
    detecion_mask = self._sigm(out_clf) > 0.7
  File "C:\Users\user\Desktop\temp\hand_tracking\hand_tracker.py", line 95, in _sigm
    return 1 / (1 + np.exp(-x) )
RecursionError: maximum recursion depth exceeded while calling a Python object
```
Any idea of how to deal with this? I am using TensorFlow 2.0, python 35 in virtualenv of anaconda. Much appreciated!

**Comment by wolterlw** [comment]
you're on master branch, right?
The code doesn't seem to have any recursive calls.
Can you run a debugger and set a breakpoint in sigm, step outside of it and see where it locks into recursion?

**Comment by antiapt** [comment]
Yes, I am on the master branch and am stepping into this. It seems like to raise this problem when calculating the [out_clf](https://github.com/wolterlw/hand_tracking/blob/0cccb81e620f602e1a8f91aaed525e20b809fdf5/hand_tracker.py#L121). This value caused the recursion issue when calculating the sigmoid.

But could you share with me your system requirement, thank you!

**Comment by antiapt** [comment]
It seems like there was an overflow error when calculating the exp() function. I converted the        [out_reg](https://github.com/wolterlw/hand_tracking/blob/0cccb81e620f602e1a8f91aaed525e20b809fdf5/hand_tracker.py#L120) and  [out_clf ](    https://github.com/wolterlw/hand_tracking/blob/0cccb81e620f602e1a8f91aaed525e20b809fdf5/hand_tracker.py#L121)into np.longdouble can it works out then.

**Comment by wolterlw** [comment]
better clip the value under `exp`

**Comment by antiapt** [comment]
Thanks for your suggestion, will try this.

**Comment by wolterlw** [comment]
so?
